name: math_notes
description: Math Notes Cupertino web host.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  web: 1.1.1
  multi_split_view: 3.6.2
  path: 1.9.1
  reorderable_grid: 1.0.13
  popover: 0.4.0
  flex_color_picker: 4.0.0
  pull_down_button: 0.10.2
  lucide_icons_flutter: ^3.1.20
  toastification: 3.2.0
  provider: 6.1.5
  intl: 0.20.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: ui_fonts/Inter-Regular.ttf
        - asset: ui_fonts/Inter-Medium.ttf
          weight: 500
        - asset: ui_fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: ui_fonts/Inter-Bold.ttf
          weight: 700
    - family: NoteText
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: Noto Sans Arabic
      fonts:
        - asset: generated_fonts/NotoSansArabic-Regular.ttf
    - family: Noto Sans Hebrew
      fonts:
        - asset: generated_fonts/NotoSansHebrew-Regular.ttf
    - family: Noto Sans Devanagari
      fonts:
        - asset: generated_fonts/NotoSansDevanagari-Regular.ttf
    - family: Noto Sans Symbols2
      fonts:
        - asset: generated_fonts/NotoSansSymbols2-Regular.ttf
  assets:
    - fonts/OFL.txt
    - ui_fonts/OFL.txt
